FROM python:3.10.10-slim-buster

WORKDIR /usr/src/app

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN apt-get update \
  && apt-get -y install netcat gcc cron \
  && apt-get clean \
  && apt-get install  -y coinor-cbc coinor-libcbc-dev

RUN pip install --upgrade pip
RUN pip install pipenv==v2021.5.29 --no-cache-dir
COPY Pipfile* ./
RUN pipenv install --dev --system --deploy

COPY . .